# Generated by Django 5.0.7 on 2025-02-19 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0002_payment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="payed_course",
            new_name="course",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="date_of_pay",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="payed_lesson",
            new_name="lesson",
        ),
    ]
