# Generated by Django 5.0.7 on 2025-02-27 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0003_rename_payed_course_payment_course_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
