# Generated by Django 5.0.7 on 2025-02-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="link_to_video",
            field=models.URLField(blank=True, null=True),
        ),
    ]
