# Generated by Django 5.0.7 on 2025-03-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_alter_lesson_link_to_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="link_to_video",
            field=models.URLField(blank=True, null=True),
        ),
    ]
